-- Clientes: columnas visibles; IDs locales, campos adicionales no observados.
-- Ejecutar solo en una base nueva con db/schema.sql aplicado.
BEGIN;
INSERT INTO clients(name,ruc,phone,email) VALUES('Ada Alvarenga',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Adriana Galeano',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Adriana Sanchez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Agustina Dominguez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Aida Gaspar',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Alan Riella',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Alba Cristaldo',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Alejandra Biederman',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Alejandra Garcia',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Alejandra Silva',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Alejandro Troche',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Alex',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Alexia Martinez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Alia Haifuch',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Alicia Duarte',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Alicia Martinez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Alison Coronel',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Ana Dos Santos',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Ana Fuentes',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Ana Giumarresi',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Ana Simon',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Ana Simon',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Anabella Jara',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Analia Gomez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Andrea Britez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Andrea Britos',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Andrea Gimenez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Andrea Melgarejo',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Andrea Riquelme',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Andrea Velazquez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Angel Amarilla',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Angel Zaracho',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Angeles Benitez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Angelica Lencina',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Angelica Muñoz',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Angy',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Antonella Cassacia',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Antonella Ozorio',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Ara Samudio',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Araceli Alvarez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Araceli Cabrera',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Ariana Aguilar',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Aurora',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Azul Ferreira',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Beatriz Orteman',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Belen Cabrera',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Belen Ortega',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Beli Galeano',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Betania Ortigoza',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Betania Pedrozo',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Betania Ramirez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Betina Benegochea',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Bianca Lopez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Brisa Gonzalez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Bruno Resquin',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Camila Herrera',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Camila Jimenez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Camila Pesoa',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Carla Paez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Carolina Irrazabal',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Carolina Torales',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Cecilia Mora',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Cesar Nuñez','3186925-4',NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Chiara Perez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Cindy Caballero',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Cindy Roig',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Cinthia Lezcano',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Cinthia Martinez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Clarisse Fugarazzo','3427252-6',NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Claudia Gimenez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Claudia Patiño',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Claudia Rolon',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Claudio Candia','3756234-7','0981333399','claudio.dx@gmail.com');
INSERT INTO clients(name,ruc,phone,email) VALUES('Cristian Victor',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Cristina Ramirez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Cynthia Alonso',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Cynthia Peralta',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Dahiana Gomez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Daniel F',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Daniel Vazquez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Dea Aguinaraga',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Despina Iliav',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Deysi Colman',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Deysi Vega',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Diana Jara',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Diana Ramirez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Diego Rojas',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Dora Torales',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Dra Karina Brizuela',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Eli Contadora',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Eliana Duarte',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Elizabeth Kennedy',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Estela Candia',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Estela Coronel',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Ester Cabanas',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Eva Gonzalez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Evelin Imber',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Ever Stump',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Fabi Verdina',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Fabricio Barrios',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Fabricio Bernabe',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Faten Sleiman',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Fatima Ferloni',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Fatima Fernandez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Fatima Juvinel',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Felicita Maldonado',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Fernanda Romero',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Fernanda Salinas',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Fernando Ribeiro',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Florencia Capurro',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Florencia Gimenez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Francisco',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Gabriela Robertti',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Gabriela Zarate',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Gaby Puyol',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Gina Zelaya',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Giohanna M',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Giovana Candia',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Giovanni Cristaldo',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Giselle Gonzalez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Gloria Dominguez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Grace Jara',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Graciela Benitez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Graciela Ortiz',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Graciela Rodriguez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Griselda Garcia',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Guadalupe Yinde',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Guillermo Raquel',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Hector Olmedo',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Henry Moriya',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Hija Rocio Cabral',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Ingrid Panza',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Isabel Valdez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Janira Medina',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Javier Vargas',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Jazmin Caceres',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Jazmin Ramirez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Jazmin Sanabria',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Jessica Harder',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Jessica Rozzi',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Jeysson Radtke',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Jimena Lopez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Jimena Verdina',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Joaquin feliciangeli',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Joaquina Insfran',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Johana Araujo',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Johana Balmaceda',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Jonathan',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Jorge Perez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Jose Balvera',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Jose Riquelme',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Juan Candia',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Juanita',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Julissa Armoa',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Jully',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Justa Cazafu',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Karen Banks',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Karen Garay','4582169-0',NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Karina Ojeda',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Karina Ortiz','3274975-9','0981483002',NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Karol Britez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Kimmie Nishie',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('LIC Natalia',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Larisse Mencia',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Laura Aranda',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Laura Lopez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Leonor Villalba',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Leticia Altamirano',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Leticia Candia','3756232-9','0981537543',NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Lia',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Lilian Martinez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Liliana Cazal',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Liliana Cuellar',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Linda Wagener',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Liz Aguilera',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Lizette',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Lizza Gonzalez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Lizzete Sardi',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Lorena Mendez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Lorena Benitez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Lourdes Ferreira',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Lourdes Guerrero',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Lourdes Marinoni',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Lourdes Pino',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Lucia Muñoz',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Lucina Vera',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Ludmila Lezcano','4697468-7',NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Lujan Garcia',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Lujan Pereira',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mabel Lopez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mama Maria Caceres',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mama Monica Martinez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mama Sheyla Parra',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mama de Chiara',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mara Casco',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mara Godoy',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mara Marelli',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mara Segovia',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Marcelo Candia',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Marcelo Gonzalez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Marcelo Sosa',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Marci Oviedo',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Marcia Cassera',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Margarita Yegros',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Maria Antonia',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Maria Aquino',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Maria Caceres',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Maria Liz Garcete',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Maria Rosa Vazquez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Maria Victoria Sosa',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mariana Barrios',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mariana Ortiz',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mariano argentina',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Marido Liz',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mariela Acosta',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Marilin Acosta',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mario Cuevas',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Marisol Roman',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Marlene Espinoza',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Marlene Nancy Mendez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Marta',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Martin Valdez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Marvin aleman',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mary Prada',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mateo Amigo',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mateo Medina',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mauricio Caceres',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mechi',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Meli Cuenca',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mijal Lara',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Milan',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Milena Ojeda',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Milner',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mirian Gonzalez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mirna Sanabria','3363025-9',NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mirtha argentina',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Mistica Ayala',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Monica Lopez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Monica Martinez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Monica Rodriguez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Monika Penner',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Monserrat Zarate',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Muriel Garcia',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Nadia Arguello',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Nancy Arteta',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Natalia Acuña',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Natalia Antunez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Natalia Maldonado',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Natalia Paredes',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Natalia Vallejos',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Nathali Duarte',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Nayda Caballero',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Nayeli',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Nelida Colman',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Nicole Lovera',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Novio Ana',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Nuvia Piñanez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Obdulia Coronel',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Olga Colman',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Ornella Fasano',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Pablo Fernandez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Pamela Caffarena',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Pamela Lugo',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Paola Costas',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Paola Robertti',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Paola Salinas',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Patricia Alvarez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Patricia Villalba',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Paula Ibarrola',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Paulina Silva',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Paz',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Paz Benitez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Pedro',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Perla Redes',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Raquel Lezcano',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Raquel Martinez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Rebeca Garcete',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Rebeca velilla',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Roberto Marinoni',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Rocio Cabral',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Rocio Cabrera',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Rocio Miño',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Roisa Jara',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Romina Martinez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Romina leon',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Rosa Alvarez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Rosa Paiva',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Rossana Alvarenga',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Rossana Ayala',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Rossana Barboza',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Rossana Pino',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Ruth Cuquejo',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Sabrina Muñoz',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Sandra Gimenez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Sanie Escobar',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Sara Gonzalez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Sheyla Parra',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Shirley Irala',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Silvia Acevedo',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Silvia Adriana Caceres',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Sissi Ayala',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Sonia Oviedo','868804-4',NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Sonia Sanabria',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Sra Ani',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Sthephani Templey',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Susana Ruiz',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Sussana Romero',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Tania Rolon',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Tatiana Montaño',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Teresa Bavera',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Teresa Rodas',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Teresita Ortiz',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Tomas Martinez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Valentina Romero',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Valeria Gomez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Vanessa Barrios',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Veronica Ramirez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Vicky',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Victor',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Victor Narvaez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Victoria Gustafson',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Victoria Mendez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Vivian Benitez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Viviana Soloaga',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Yami Aguilera',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Yamila Salinas',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Yanina Barreto',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Yemima Dominguez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Yessenia Ayala',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Yohana Laca',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('Yoryi Gomez',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('juanse',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('silvia Raquel Aguero','1496126-1',NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('sra Liz',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('tia Marita',NULL,NULL,NULL);
INSERT INTO clients(name,ruc,phone,email) VALUES('vania cuenca',NULL,NULL,NULL);
COMMIT;
