export async function seed(db) {
 if ((await db.query('SELECT id FROM payment_methods LIMIT 1')).rows.length) return;
 for (const [id,name] of [['efectivo','Efectivo'],['debito','Tarjeta Débito'],['credito','Tarjeta de Crédito'],['transferencia','Transferencia'],['voucher','Voucher']]) await db.query('INSERT INTO payment_methods(id,name) VALUES($1,$2)',[id,name]);
 // Tasas inferidas de pares bruto/real visibles. Los importes históricos se importan literalmente.
 await db.query("UPDATE payment_methods SET fee_percent=2.2 WHERE id='debito'");
 await db.query("UPDATE payment_methods SET fee_percent=3.3 WHERE id='credito'");
 for(const [name,color] of [['Laura Ortiz','#a67fd4'],['Lenny Aguiar','#60a5fa'],['Micaela Fines','#f59e0b'],['Tamara Rojas','#34d399']]) await db.query('INSERT INTO professionals(name,color) VALUES($1,$2)',[name,color]);
 const damas=['Baño de Luna Durazno','Baño de Luna Normal','Combo Gestante','Drenaje Corporal + Copa Sueca','Drenaje Linfatico - completo + rostro','Drenaje Linfatico - cuerpo completo','Exfoliacion e hidratacion','Exfoliacion e hidratacion con Masaje Express','Manta mas drenaje detox','Masaje Combinado (relax + descontracturante)','Masaje Combinado profundo','Masaje Descontracturante','Masaje Descontracturante 30m','Masaje Profundo','Masaje Reductor - 1 Zona','Masaje Reductor - 2 Zonas','Masaje Reductor - cuerpo completo','Masaje Relajante','Masaje con Piedras Calientes','Masaje post Lipo','Metodo Cielo y Tierra SPA (3MH)','Reflexologia','Vela Slim - 1 zona','Vela Slim - 2 zona','Vela Slim - 3 zona','Vela Slim 1 Zona + Masaje 2 Zonas'];
 const caballero=['Drenaje Linfatico - completo + rostro','Drenaje Linfatico - cuerpo completo','Masaje Combinado (relax + descontracturante)','Masaje Combinado profundo','Masaje Descontracturante','Masaje Descontracturante 30m','Masaje Profundo','Masaje Reductor - 1 Zona','Masaje Reductor - 2 Zonas','Masaje Reductor - cuerpo completo','Masaje Relajante','Masaje con Piedras Calientes','Metodo Cielo y Tierra SPA (3MH)','Reflexologia'];
 const faciales=['Exoxomas + ADN de Salmon','Limpieza e hidratación profunda','Limpieza e hidratación profunda + Mascara Led','Limpieza facial express','Limpieza facial express + Mascara Led','Limpieza profunda + Radiofrecuenta','Limpieza profunda + electroporación','Limpieza profunda + mesoexfoliación','Limpieza profunda mas peeling','Peeling 3D','Peeling facial','Peeling facial retinplast','Radiofrecuencia fraccionada','Tratamiento en Gluteos'];
 const prices={'Damas':{'Baño de Luna Durazno':260000,'Drenaje Linfatico - cuerpo completo':160000,'Exfoliacion e hidratacion':140000,'Masaje Combinado (relax + descontracturante)':200000,'Masaje Combinado profundo':240000,'Masaje Descontracturante':170000,'Masaje Reductor - 1 Zona':140000,'Masaje Reductor - 2 Zonas':160000,'Masaje Reductor - cuerpo completo':160000,'Masaje Relajante':150000,'Metodo Cielo y Tierra SPA (3MH)':300000},'Caballero':{'Masaje Reductor - 1 Zona':150000},'Faciales':{'Limpieza e hidratación profunda':200000,'Limpieza profunda mas peeling':250000,'Radiofrecuencia fraccionada':300000,'Tratamiento en Gluteos':180000}};
 for(const [category,names] of [['Damas',damas],['Caballero',caballero],['Faciales',faciales]]) for(const name of names) await db.query('INSERT INTO services(name,category,price) VALUES($1,$2,$3)',[name,category,prices[category]?.[name]??null]);
 for(const [name,type,stock,minimum,price,commission] of [['Almohaditas','almohaditas',0,1,80000,0],['AntiFaz','antifaz',0,1,50000,0],['Crema Corporal','Crema Corporal',0,0,0,0],['Crema Hidrante','Crema Hidrante',0,0,0,0],['Espuma de limpieza','Espuma de limpieza',0,0,0,0],['Gel de Limpieza','gel de limpieza',3,0,0,0],['Protecto Solar','Protecto Solar',0,0,0,0],['Serum','Serum',0,0,0,0],['Tonico','spry',0,1,150000,10]]) await db.query('INSERT INTO products(name,type,stock,minimum,price,commission_percent) VALUES($1,$2,$3,$4,$5,$6)',[name,type,stock,minimum,price,commission]);
}
